apiVersion: apps/v1
kind: Deployment
metadata:
  name: mussubotti
  namespace: mussubot
  labels:
    app: mussubotti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mussubotti
  template:
    metadata:
      labels:
        app: mussubotti
    spec:
      containers:
      - name: mussubotti
        image: ${IMAGE_REPO}:${IMAGE_TAG}
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          runAsUser: 10000
          capabilities:
            drop: [ALL]
        envFrom:
        - secretRef:
            name: mussubotti-secrets
        - configMapRef:
            name: mussubotti-config
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep mussubotti | grep -v grep
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps aux | grep mussubotti | grep -v grep
          initialDelaySeconds: 5
          periodSeconds: 10 